import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Lemon } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Funkit',
  description: 'Generated by Next.js',
}

const lemon = Lemon({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
});

export default function RootLayout({
    children, 
    }: {
        children: React.ReactNode
    }) {
    return (
        <html lang="en" className={lemon.className}>
        <body>
            <div className="pageWrapper">
                {children}
            </div>
            <footer>
                <p>Våra sponsorer</p>
            </footer>
        </body>
        </html>
    )
}
